name: elearning_events_app
description: "A comprehensive e-learning events application with Flutter and SQLite"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  sqflite: ^2.3.0
  path: ^1.9.0
  bcrypt: ^1.1.3
  flame: ^1.17.0
  # UI and animations
  google_fonts: ^6.1.0
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  # State management
  provider: ^6.1.1
  
  # Image handling
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Maps and location
  maps_launcher: ^3.0.0+1
  url_launcher: ^6.1.14
  flutter_map: ^6.1.0

  # Utilities
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/www/

  
  # Uncomment if you add assets
  # assets:
  #   - images/
  #   - fonts/
  
  # Uncomment if you add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
